### ISSUE TITLE
javascript-example app failure

### ISSUE THREAD

**Issue by nathan-at-least** [clovyr/clovyr#1]
(Apologies if this isn't the right repo.)

I just tried to dive into the recommended first example on the app, but ran into this screen:

![image](https://user-images.githubusercontent.com/4369700/98063890-65645780-1e94-11eb-97ba-16eb8b83252d.png).

Is there a better place to send user feedback for the app?

**Comment by patrickmn** [comment]
Hi Nathan!

Try reloading the entire site?

(Occasionally there is a timing issue where it tries to create the access session before the instance is ready. If you reload the website, it will recreate that session and the issue should go away.)

Feel free to email me with any feedback, patrick at clovyr dot io. If you run into any more issues we can try to address them quickly.
